name: Build

on: [push, pull_request]

permissions:
  checks: write

jobs:
  check-format-rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo fmt -- --check
        uses: qRoC/cargo-actions@v1
        with:
          command: fmt
          args: -- --check
          token: ${{ secrets.GITHUB_TOKEN }}
  check-rust:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macOS]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo check
        uses: qRoC/cargo-actions@v1
        with:
          command: check
          token: ${{ secrets.GITHUB_TOKEN }}
  build-rust-artifacts:
    # only master branch
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macOS]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo build --release
        uses: qRoC/cargo-actions@v1
        with:
          command: build
          args: --release
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: |
            target/release/recent-messages2
            target/release/recent-messages2.exe
  check-format-prettier:
    runs-on: ubuntu-latest
    container: node:22-bookworm
    steps:
      - uses: actions/checkout@v4
      - run: cd web && npm ci
      # If updating this command, make sure to update the same command in /scripts/reformat.sh too
      - run: ./web/node_modules/.bin/prettier --check --ignore-path ".gitignore" "**/*.md" "**/*.tsx" "**/*.yml" "**/*.json"
  build-web:
    runs-on: ubuntu-latest
    container: node:${{ matrix.node }}-bullseye
    strategy:
      matrix:
        node: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - run: cd web && npm ci
      - run: cd web && npm run build
      - uses: actions/upload-artifact@v4
        # only master branch
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          name: web
          path: web/dist/
