name: Build

on: [push, pull_request]

jobs:
  check-format-rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
  check-rust:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macOS]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  build-rust-artifacts:
    # only master branch
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macOS]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo build --release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: |
            target/release/recent-messages2
            target/release/recent-messages2.exe
  check-format-prettier:
    runs-on: ubuntu-latest
    container: node:16-stretch
    steps:
      - uses: actions/checkout@v2
      - run: cd web && npm ci
      - run: ./web/node_modules/.bin/prettier --check --ignore-path ".gitignore" "**/*.md" "**/*.tsx" "**/*.yml" "**/*.json"
  build-web:
    runs-on: ubuntu-latest
    container: node:${{ matrix.node }}-stretch
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - run: cd web && npm ci
      - run: cd web && npm run build
      - uses: actions/upload-artifact@v2
        # only master branch
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          name: web
          path: web/dist/
